# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "simple sale pop"
client_id = "31e32703ad9063d42ff2611e60d06893"
application_url = "https://say-dont-give-papua.trycloudflare.com/auth/shopify"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://say-dont-give-papua.trycloudflare.com/auth/shopify/callback",
  "https://say-dont-give-papua.trycloudflare.com/authSa/shopify/callback",
  "https://say-dont-give-papua.trycloudflare.com/auth/shopify/embed/callback",
  "https://localhost:3000/auth/shopify/callback",
  "https://localhost:3000/authSa/shopify/callback",
  "https://localhost:3000/auth/shopify/embed/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "avada-first.myshopify.com"
